### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by husai033** [punyajoy/DE-LIMIT#2]
I got the following error when I use your dehatebert-mono-arabic with [Chris McCormick code](https://colab.research.google.com/drive/1pTuQhug6Dhl9XalKB0zUGf4FIdYFlpcX#scrollTo=guw6ZNtaswKc)  :
RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([2, 768]) from checkpoint, the shape in current model is torch.Size([3, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).

**Comment by punyajoy** [comment]
Hi, can u please send a more detailed version of your code. I think the main issue is our model had two classes (_Hate and Normal_) but yours one has three classes. You need to separate the transformer part of the model and add a separate linear classifier (_with three classes as output_) to make it work.

**Comment by husai033** [comment]
Yes, my dataset has three classes. Do you have a sample code for similar situation?

**Comment by SaiSakethAluru** [comment]
Hi @husai033, 
I have added a sample code file for modifying the model to work with more than 2 class classification. You can find the example file [here](https://github.com/punyajoy/DE-LIMIT/blob/master/Example/N_Class_model.ipynb).
Hope this helps.

**Comment by punyajoy** [comment]
I am closing the issue for now :slightly_smiling_face:

**Comment by husai033** [comment]
Thank you so much
